POST http://localhost:5000/users/ HTTP/1.1
Content-Type: application/json

{
  "gender": "female",
  "name": {
      "title": "Ms",
      "first": "Svenja",
      "last": "Mühl"
  },
  "location": {
      "street": {
          "number": 3489,
          "name": "Mühlenweg"
      },
      "city": "Burladingen",
      "state": "Baden-Württemberg",
      "country": "Germany",
      "postcode": 29671,
      "coordinates": {
          "latitude": "-47.4427",
          "longitude": "133.7700"
      },
      "timezone": {
          "offset": "0:00",
          "description": "Western Europe Time, London, Lisbon, Casablanca"
      }
  },
  "email": "svenja.muhl@example.com",
  "login": {
      "uuid": "e9b75b20-3f89-4a91-9b7b-833abd181189",
      "username": "sadleopard291",
      "password": "joanna",
      "salt": "0GKOMe1U",
      "md5": "4cad48f068392a8518197a0bcd7eb4bf",
      "sha1": "52542d0699a86eff2482279443127ebdb2dfd974",
      "sha256": "2f0e888cdacd63750562df2516b5817d20ac1c3fd7b265c0dc579e78fe625809"
  },
  "dob": {
      "date": "1957-07-25T21:36:45.235Z",
      "age": 65
  },
  "registered": {
      "date": "2015-12-22T20:48:36.151Z",
      "age": 7
  },
  "phone": "0815-0155194",
  "cell": "0175-1631684",
  "picture": {
      "large": "https://randomuser.me/api/portraits/women/66.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/66.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/66.jpg"
  },
  "nat": "DE"
}