POST http://localhost:5000/api/phones HTTP/1.1
Content-Type: application/json

{
  "model": "S22",
  "brand": "Samsung",
  "productionYear": 2022,
  "ram": 8,
  "cpu": "Qualcome Snapdragon 4 cores",
  "screenDiagonal": 6.67,
  "isnfc": true
}