# Check existing user - 200, user
PATCH http://localhost:5000/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "doe@example.com",
  "passwordHash": "admin",
  "birthday": "1995-05-27"
}

# Check noexisting user - 404, user not fount
PATCH http://localhost:5000/api/users/100 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "doe@example.com",
  "passwordHash": "admin",
  "birthday": "1995-05-27"
}

# Check existing user with uncorrect info - 500, server error
PATCH http://localhost:5000/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "doe",
  "passwordHash": "admin",
  "birthday": "1995-05-27"
}