module.exports.usersController = require('./usersController.js')
module.exports.phoneController = require('./phoneController.js')
module.exports.tasksController = require('./taskController.js')
module.exports.topicsController = require('./topicsController.js')
module.exports.classesController = require('./classesController.js')